import CoreGraphics
import CoreImage
import Darwin
import Foundation
import ImageIO
import UniformTypeIdentifiers

struct VideoFrameAllocationInput: Equatable, Sendable {
    let durationSeconds: Double
    let availableCandidateCount: Int
}

enum VideoFrameAllocationError: Error, Equatable {
    case invalidInput(index: Int)
    case insufficientBudgetForClipCoverage(required: Int, available: Int)
}

enum LocalFileCopyStrategy: Equatable, Sendable {
    case copyOnWriteClone
    case streamed
}

struct GlobalFrameTargets: Equatable, Sendable {
    let videoTargets: [Int]
    let photoTarget: Int

    var totalTargetCount: Int { videoTargets.reduce(0, +) + photoTarget }
}

struct IndexedFrameAnalysis: Sendable {
    let index: Int
    let analysis: FrameExtractionAnalysis
}

final class WeightedVideoAnalysisProgress: @unchecked Sendable {
    private let lock = NSLock()
    private let weights: [Double]
    private let totalWeight: Double
    private let base: Double
    private let span: Double
    private let report: @Sendable (Double) -> Void
    private var fractions: [Double]
    private var lastReported: Double?

    init(
        weights: [Double],
        base: Double,
        span: Double,
        report: @escaping @Sendable (Double) -> Void
    ) {
        let sanitizedWeights = weights.map {
            $0.isFinite && $0 > 0 ? $0 : 1
        }
        self.weights = sanitizedWeights
        self.totalWeight = max(1, sanitizedWeights.reduce(0, +))
        self.base = base
        self.span = span
        self.report = report
        self.fractions = [Double](repeating: 0, count: weights.count)
    }

    func update(index: Int, fraction: Double) {
        lock.lock()
        defer { lock.unlock() }
        guard fractions.indices.contains(index) else { return }
        let clamped = fraction.isFinite ? min(max(fraction, 0), 1) : 0
        fractions[index] = max(fractions[index], clamped)
        let aggregate = zip(weights, fractions).reduce(0.0) {
            $0 + $1.0 * $1.1
        } / totalWeight
        let next = base + span * aggregate
        guard lastReported.map({ next > $0 }) ?? true else { return }
        lastReported = next
        report(next)
    }
}

extension PipelineRunner {
    static func shouldFallBackFromCloneError(_ code: Int32) -> Bool {
        code == ENOTSUP || code == EXDEV
    }

    static func videoAnalysisConcurrency(
        threadLimit: Int,
        videoCount: Int
    ) -> Int {
        guard videoCount > 0 else { return 1 }
        return min(videoCount, 4, max(1, threadLimit / 2))
    }

    func analyzeVideoSources(
        _ sources: [FrameExtractionSource],
        options: FrameExtractionOptions,
        targetCounts: [Int],
        maximumConcurrency: Int,
        progress: @escaping @Sendable (Int, Double) -> Void
    ) async throws -> [FrameExtractionAnalysis] {
        guard !sources.isEmpty,
              sources.count == targetCounts.count,
              targetCounts.allSatisfy({ $0 > 0 }) else {
            throw PipelineError.invalidInput
        }
        let workerCount = min(sources.count, max(1, maximumConcurrency))
        return try await withThrowingTaskGroup(
            of: IndexedFrameAnalysis.self,
            returning: [FrameExtractionAnalysis].self
        ) { group in
            var nextIndex = 0
            var results = [FrameExtractionAnalysis?](
                repeating: nil,
                count: sources.count
            )

            func submit(_ index: Int) {
                let source = sources[index]
                var sourceOptions = options
                sourceOptions.targetCount = targetCounts[index]
                group.addTask {
                    let extractor = FrameExtractor()
                    let analysis = try await extractor.analyze(
                        source,
                        options: sourceOptions,
                        progress: { fraction, _ in
                            progress(index, fraction)
                        }
                    )
                    return IndexedFrameAnalysis(index: index, analysis: analysis)
                }
            }

            while nextIndex < workerCount {
                submit(nextIndex)
                nextIndex += 1
            }
            while let result = try await group.next() {
                results[result.index] = result.analysis
                if nextIndex < sources.count {
                    submit(nextIndex)
                    nextIndex += 1
                }
            }
            guard results.allSatisfy({ $0 != nil }) else {
                throw PipelineError.invalidInput
            }
            return results.compactMap { $0 }
        }
    }
    // Selected-frame names and group identifiers are generated by EasySplat. Four
    // MiB allows more than one KiB per entry at the 3,000-frame release boundary.
    private static let maximumSelectedFrameManifestBytes = 4 * 1_024 * 1_024

    struct SelectedFrameGroup: Sendable {
        let id: String
        let frames: [URL]
        let isVideo: Bool
    }

    struct SelectedFrameMapping: Codable, Sendable {
        let outputFileName: String
        let groupId: String
        let isVideo: Bool
        let timestampSeconds: Double?
        let lowLightExposureEV: Double?

        init(
            outputFileName: String,
            groupId: String,
            isVideo: Bool,
            timestampSeconds: Double? = nil,
            lowLightExposureEV: Double? = nil
        ) {
            self.outputFileName = outputFileName
            self.groupId = groupId
            self.isVideo = isVideo
            self.timestampSeconds = timestampSeconds
            self.lowLightExposureEV = lowLightExposureEV
        }
    }

    var supportedImageExtensions: Set<String> {
        PhotoInputPreflight.supportedExtensions
    }

    func isHeicImage(_ url: URL) -> Bool {
        let ext = url.pathExtension.lowercased()
        return ext == "heic" || ext == "heif"
    }

    func selectedImagesHaveUniformPixelDimensions(_ images: [URL]) throws -> Bool {
        var expectedDimensions: (width: Int, height: Int)?
        for image in images {
            guard let source = CGImageSourceCreateWithURL(image as CFURL, nil),
                  let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil)
                    as? [CFString: Any],
                  let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
                  let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
                  width > 0,
                  height > 0 else {
                throw PipelineError.imageTranscodeFailed(
                    "Failed to inspect selected image: \(image.lastPathComponent)"
                )
            }
            let dimensions = (width: width, height: height)
            if let expectedDimensions,
               expectedDimensions.width != dimensions.width
                || expectedDimensions.height != dimensions.height {
                return false
            }
            expectedDimensions = dimensions
        }
        return expectedDimensions != nil
    }

    func transcodeHeicToJpeg(source: URL, destination: URL) throws {
        guard let sourceRef = CGImageSourceCreateWithURL(source as CFURL, nil) else {
            throw PipelineError.imageTranscodeFailed("Failed to read HEIC image: \(source.lastPathComponent)")
        }

        let props = CGImageSourceCopyPropertiesAtIndex(sourceRef, 0, nil) as? [CFString: Any]
        let width = (props?[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue ?? 0
        let height = (props?[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue ?? 0
        let maxDim = max(1, max(width, height))
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxDim,
            kCGImageSourceShouldCache: false
        ]

        guard let cgImage = CGImageSourceCreateThumbnailAtIndex(sourceRef, 0, options as CFDictionary) else {
            throw PipelineError.imageTranscodeFailed("Failed to decode HEIC image: \(source.lastPathComponent)")
        }

        guard let destRef = CGImageDestinationCreateWithURL(destination as CFURL, UTType.jpeg.identifier as CFString, 1, nil) else {
            throw PipelineError.imageTranscodeFailed("Failed to create JPEG output: \(destination.lastPathComponent)")
        }

        let destOptions: [CFString: Any] = [
            kCGImageDestinationLossyCompressionQuality: 0.95
        ]
        CGImageDestinationAddImage(destRef, cgImage, destOptions as CFDictionary)
        guard CGImageDestinationFinalize(destRef) else {
            throw PipelineError.imageTranscodeFailed("Failed to write JPEG image: \(destination.lastPathComponent)")
        }
    }

    // Earlier versions copied HEIC photos into Selected/ directly. Geometry tools expect
    // JPEG or PNG, so resumed projects transcode those files in place.
    func normalizeSelectedImagesForTooling(paths: ProjectPaths) throws -> Int {
        let fm = FileManager.default
        guard fm.fileExists(atPath: paths.framesSelectedURL.path) else { return 0 }

        let files = try fm.contentsOfDirectory(at: paths.framesSelectedURL, includingPropertiesForKeys: nil)
            .filter { !$0.hasDirectoryPath }

        var renamed: [String: String] = [:]
        var converted = 0
        for file in files where isHeicImage(file) {
            let newName = file.deletingPathExtension().lastPathComponent + ".jpg"
            let dest = paths.framesSelectedURL.appendingPathComponent(newName)

            if !fm.fileExists(atPath: dest.path) {
                try transcodeHeicToJpeg(source: file, destination: dest)
            }
            // Ensure downstream tools don't see a mix of formats with duplicate basenames.
            try? fm.removeItem(at: file)
            renamed[file.lastPathComponent] = newName
            converted += 1
        }

        if converted > 0,
           fm.fileExists(atPath: paths.framesSelectedManifestURL.path),
           let manifest = try? loadSelectedFrameManifest(from: paths.framesSelectedManifestURL) {
            let updated = manifest.map { entry in
                guard let newName = renamed[entry.outputFileName] else { return entry }
                return SelectedFrameMapping(
                    outputFileName: newName,
                    groupId: entry.groupId,
                    isVideo: entry.isVideo,
                    timestampSeconds: entry.timestampSeconds,
                    lowLightExposureEV: entry.lowLightExposureEV
                )
            }
            try saveSelectedFrameManifest(updated, to: paths.framesSelectedManifestURL)
        }

        return converted
    }

    func downsampleSelectedFrames(to targetCount: Int, paths: ProjectPaths) throws -> [URL]? {
        guard targetCount > 0 else { return nil }
        let existing = try loadImages(in: paths.framesSelectedURL)
        guard existing.count > targetCount else { return nil }
        let reduced = evenlySpacedFrames(existing, targetCount: targetCount)

        let tempSelected = paths.framesSelectedURL.deletingLastPathComponent()
            .appendingPathComponent("selected_retry", isDirectory: true)
        try resetDirectory(tempSelected)
        let newSelection = try copySelected(reduced, to: tempSelected)
        removeIfExists(paths.framesSelectedURL)
        try FileManager.default.moveItem(at: tempSelected, to: paths.framesSelectedURL)
        if FileManager.default.fileExists(atPath: paths.framesSelectedManifestURL.path),
           let manifest = try? loadSelectedFrameManifest(from: paths.framesSelectedManifestURL) {
            let manifestByFile = Dictionary(manifest.map { ($0.outputFileName, $0) }, uniquingKeysWith: { first, _ in first })
            var updated: [SelectedFrameMapping] = []
            updated.reserveCapacity(newSelection.count)
            for (index, original) in reduced.enumerated() where index < newSelection.count {
                let oldName = original.lastPathComponent
                guard let entry = manifestByFile[oldName] else { continue }
                let newName = newSelection[index].lastPathComponent
                updated.append(SelectedFrameMapping(
                    outputFileName: newName,
                    groupId: entry.groupId,
                    isVideo: entry.isVideo,
                    timestampSeconds: entry.timestampSeconds,
                    lowLightExposureEV: entry.lowLightExposureEV
                ))
            }
            try? saveSelectedFrameManifest(updated, to: paths.framesSelectedManifestURL)
        }
        return try loadImages(in: paths.framesSelectedURL)
    }

    func copySelected(
        groups: [SelectedFrameGroup],
        to directory: URL,
        manifestURL: URL,
        maxDimension: CGFloat,
        progress: ((Double, String) -> Void)? = nil
    ) throws -> (frames: [URL], manifest: [SelectedFrameMapping]) {
        let fm = FileManager.default
        var output: [URL] = []
        var manifest: [SelectedFrameMapping] = []
        let total = groups.reduce(0) { $0 + $1.frames.count }
        var index = 0
        var copied = 0
        var lowLightContext: CIContext?
        for group in groups {
            for frame in group.frames {
                try Task.checkCancellation()
                let sourceExt = frame.pathExtension.lowercased()
                let destExt: String = {
                    if sourceExt.isEmpty { return "jpg" }
                    if sourceExt == "heic" || sourceExt == "heif" { return "jpg" }
                    return sourceExt
                }()
                let dest = directory.appendingPathComponent(String(format: "frame_%06d.%@", index, destExt))
                if fm.fileExists(atPath: dest.path) { try fm.removeItem(at: dest) }
                let lowLightExposureEV = try copySelectedFrame(
                    source: frame,
                    destination: dest,
                    maxDimension: maxDimension,
                    context: &lowLightContext
                )
                output.append(dest)
                manifest.append(SelectedFrameMapping(
                    outputFileName: dest.lastPathComponent,
                    groupId: group.id,
                    isVideo: group.isVideo,
                    timestampSeconds: group.isVideo
                        ? FrameExtractor.timestampSeconds(from: frame.lastPathComponent)
                        : nil,
                    lowLightExposureEV: lowLightExposureEV
                ))
                index += 1
                copied += 1
                if let progress, total > 0, copied % 5 == 0 || copied == total {
                    let fraction = Double(copied) / Double(total)
                    progress(fraction, "Copying selected frames \(copied)/\(total)")
                }
            }
        }
        try saveSelectedFrameManifest(manifest, to: manifestURL)
        return (output, manifest)
    }

    private func copySelectedFrame(
        source: URL,
        destination: URL,
        maxDimension: CGFloat,
        context: inout CIContext?
    ) throws -> Double? {
        let exposureEV = (try? FrameScoring.scoreFrame(at: source).lowLightExposureEV) ?? 0
        guard let sourceRef = CGImageSourceCreateWithURL(source as CFURL, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(sourceRef, 0, nil) as? [CFString: Any],
              let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
              width > 0,
              height > 0 else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to inspect selected image: \(source.lastPathComponent)"
            )
        }
        let largestDimension = max(width, height)
        let boundedDimension: Int
        if maxDimension.isFinite, maxDimension > 0 {
            let clampedDimension = min(CGFloat(largestDimension), maxDimension.rounded(.down))
            boundedDimension = max(1, Int(clampedDimension))
        } else {
            boundedDimension = largestDimension
        }
        let needsTranscode = exposureEV > 0
            || isHeicImage(source)
            || largestDimension > boundedDimension
        guard needsTranscode else {
            try FileManager.default.copyItem(at: source, to: destination)
            return nil
        }

        try Task.checkCancellation()
        guard let image = CGImageSourceCreateThumbnailAtIndex(
                sourceRef,
                0,
                [
                    kCGImageSourceCreateThumbnailFromImageAlways: true,
                    kCGImageSourceCreateThumbnailWithTransform: true,
                    kCGImageSourceThumbnailMaxPixelSize: boundedDimension,
                    kCGImageSourceShouldCache: false,
                ] as CFDictionary
              ) else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to decode selected image: \(source.lastPathComponent)"
            )
        }
        try Task.checkCancellation()

        let outputImage: CGImage
        if exposureEV > 0 {
            let input = CIImage(cgImage: image)
            let adjusted = input.applyingFilter(
                "CIExposureAdjust",
                parameters: [kCIInputEVKey: exposureEV]
            )
            let renderingContext = context ?? CIContext(options: [.cacheIntermediates: false])
            context = renderingContext
            guard let adjustedImage = renderingContext.createCGImage(adjusted, from: input.extent) else {
                throw PipelineError.imageTranscodeFailed(
                    "Failed to adjust low-light image: \(source.lastPathComponent)"
                )
            }
            outputImage = adjustedImage
        } else {
            outputImage = image
        }

        let outputType: UTType = destination.pathExtension.lowercased() == "png" ? .png : .jpeg
        guard let destinationRef = CGImageDestinationCreateWithURL(
            destination as CFURL,
            outputType.identifier as CFString,
            1,
            nil
        ) else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to create selected image: \(destination.lastPathComponent)"
            )
        }
        let options: [CFString: Any] = outputType == .jpeg
            ? [kCGImageDestinationLossyCompressionQuality: 0.95]
            : [:]
        CGImageDestinationAddImage(destinationRef, outputImage, options as CFDictionary)
        guard CGImageDestinationFinalize(destinationRef) else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to write selected image: \(destination.lastPathComponent)"
            )
        }
        return exposureEV > 0 ? exposureEV : nil
    }

    func saveSelectedFrameManifest(_ manifest: [SelectedFrameMapping], to url: URL) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(manifest)
        try data.write(to: url, options: [.atomic])
    }

    func loadSelectedFrameManifest(from url: URL) throws -> [SelectedFrameMapping] {
        let data = try BoundedFileReader.readRegularFile(
            at: url,
            maximumBytes: Self.maximumSelectedFrameManifestBytes
        )
        return try JSONDecoder().decode([SelectedFrameMapping].self, from: data)
    }

    func importedVideoURLs(for videoFiles: [String], paths: ProjectPaths) -> [URL] {
        var usedNames = Set<String>()
        return videoFiles.map { file in
            let source = URL(fileURLWithPath: file)
            let name = uniqueImportedVideoName(for: source, usedNames: &usedNames)
            return paths.originalsURL.appendingPathComponent(name)
        }
    }

    private func uniqueImportedVideoName(for source: URL, usedNames: inout Set<String>) -> String {
        let filename = source.lastPathComponent
        if usedNames.insert(filename.lowercased()).inserted {
            return filename
        }

        let nsName = filename as NSString
        let stem = nsName.deletingPathExtension
        let ext = nsName.pathExtension
        var suffix = 2
        while true {
            let candidate: String
            if ext.isEmpty {
                candidate = "\(stem)-\(suffix)"
            } else {
                candidate = "\(stem)-\(suffix).\(ext)"
            }
            if usedNames.insert(candidate.lowercased()).inserted {
                return candidate
            }
            suffix += 1
        }
    }

    func importInputs(
        metadata: ProjectMetadata,
        paths: ProjectPaths,
        progress: (Double, String) -> Void
    ) throws {
        var tasks: [(label: String, action: () throws -> Void)] = []

        let importedVideos = importedVideoURLs(for: metadata.input.videoFiles, paths: paths)
        for (file, dest) in zip(metadata.input.videoFiles, importedVideos) {
            let source = URL(fileURLWithPath: file)
            tasks.append((label: dest.lastPathComponent, action: {
                if try self.importedVideoNeedsCopy(dest) {
                    try self.copyFileAtomically(from: source, to: dest)
                }
            }))
        }

        if let photosFolder = metadata.input.photosFolder {
            let sourceFolder = URL(fileURLWithPath: photosFolder)
            let dest = paths.importedPhotosURL
            tasks.append((label: "Photos: \(sourceFolder.lastPathComponent)", action: {
                let photos = try PhotoInputPreflight.discoveredPhotos(in: sourceFolder)
                let inspection = try PhotoInputPreflight.inspect(photos)
                guard !inspection.validPhotos.isEmpty || metadata.input.hasVideos else {
                    throw PipelineError.invalidInput
                }
                let entries = self.importedPhotoEntries(for: inspection.validPhotos)
                if try self.importedPhotoFolderNeedsCopy(entries: entries, destination: dest) {
                    try self.copyValidPhotosAtomically(entries, to: dest)
                }
            }))
        }

        guard !tasks.isEmpty else { return }
        let total = tasks.count
        for (index, task) in tasks.enumerated() {
            try Task.checkCancellation()
            let message = "Copying input \(index + 1)/\(total): \(task.label)"
            let startFraction = Double(index) / Double(total)
            progress(startFraction, message)
            try task.action()
            let endFraction = Double(index + 1) / Double(total)
            progress(endFraction, message)
        }
    }

    func copySelected(_ frames: [URL], to directory: URL) throws -> [URL] {
        let fm = FileManager.default
        var output: [URL] = []
        for (index, url) in frames.enumerated() {
            try Task.checkCancellation()
            let sourceExt = url.pathExtension.lowercased()
            let destExt: String = {
                if sourceExt.isEmpty { return "jpg" }
                if sourceExt == "heic" || sourceExt == "heif" { return "jpg" }
                return sourceExt
            }()
            let dest = directory.appendingPathComponent(String(format: "frame_%06d.%@", index, destExt))
            if fm.fileExists(atPath: dest.path) { try fm.removeItem(at: dest) }
            if isHeicImage(url) {
                try transcodeHeicToJpeg(source: url, destination: dest)
            } else {
                try fm.copyItem(at: url, to: dest)
            }
            output.append(dest)
        }
        return output
    }

    func importedVideoNeedsCopy(_ destination: URL) throws -> Bool {
        let fm = FileManager.default
        guard fm.fileExists(atPath: destination.path) else { return true }
        let size = (try? fm.attributesOfItem(atPath: destination.path)[.size] as? NSNumber)?.int64Value ?? 0
        return size <= 0
    }

    private func importedPhotoEntries(for photos: [URL]) -> [(source: URL, fileName: String)] {
        var usedNames = Set<String>()
        return photos.map { photo in
            let filename = uniqueImportedPhotoName(for: photo, usedNames: &usedNames)
            return (photo, filename)
        }
    }

    private func uniqueImportedPhotoName(for source: URL, usedNames: inout Set<String>) -> String {
        let filename = source.lastPathComponent
        if usedNames.insert(filename.lowercased()).inserted {
            return filename
        }

        let nsName = filename as NSString
        let stem = nsName.deletingPathExtension
        let ext = nsName.pathExtension
        var suffix = 2
        while true {
            let candidate = ext.isEmpty
                ? "\(stem)-\(suffix)"
                : "\(stem)-\(suffix).\(ext)"
            if usedNames.insert(candidate.lowercased()).inserted {
                return candidate
            }
            suffix += 1
        }
    }

    func importedPhotoFolderNeedsCopy(
        entries: [(source: URL, fileName: String)],
        destination: URL
    ) throws -> Bool {
        let fm = FileManager.default
        guard fm.fileExists(atPath: destination.path) else { return true }
        try Task.checkCancellation()
        let contents = try fm.contentsOfDirectory(
            at: destination,
            includingPropertiesForKeys: [.isRegularFileKey, .fileSizeKey],
            options: [.skipsHiddenFiles]
        )
        guard contents.count == entries.count else { return true }
        let expectedNames = Set(entries.map(\.fileName))
        guard Set(contents.map(\.lastPathComponent)) == expectedNames else { return true }
        for file in contents {
            try Task.checkCancellation()
            let values = try file.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
            if values.isRegularFile != true || (values.fileSize ?? 0) <= 0 {
                return true
            }
        }
        return false
    }

    func copyFileAtomically(from source: URL, to destination: URL) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        let temp = destination.deletingLastPathComponent()
            .appendingPathComponent(".\(destination.lastPathComponent).\(UUID().uuidString).tmp")
        defer {
            if fm.fileExists(atPath: temp.path) {
                try? fm.removeItem(at: temp)
            }
        }

        try copyFileContents(from: source, to: temp)
        try Task.checkCancellation()
        if fm.fileExists(atPath: destination.path) {
            _ = try fm.replaceItemAt(destination, withItemAt: temp, backupItemName: nil, options: [])
        } else {
            try fm.moveItem(at: temp, to: destination)
        }
    }

    private func copyValidPhotosAtomically(
        _ entries: [(source: URL, fileName: String)],
        to destination: URL
    ) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        let temp = destination.deletingLastPathComponent()
            .appendingPathComponent(".\(destination.lastPathComponent).\(UUID().uuidString).tmp", isDirectory: true)
        defer {
            if fm.fileExists(atPath: temp.path) {
                try? fm.removeItem(at: temp)
            }
        }

        try fm.createDirectory(at: temp, withIntermediateDirectories: false)
        for entry in entries {
            try Task.checkCancellation()
            try copyFileContents(
                from: entry.source,
                to: temp.appendingPathComponent(entry.fileName)
            )
        }
        try Task.checkCancellation()
        if fm.fileExists(atPath: destination.path) {
            _ = try fm.replaceItemAt(destination, withItemAt: temp, backupItemName: nil, options: [])
        } else {
            try fm.moveItem(at: temp, to: destination)
        }
    }

    @discardableResult
    func copyFileContents(
        from source: URL,
        to destination: URL
    ) throws -> LocalFileCopyStrategy {
        try Task.checkCancellation()
        let fm = FileManager.default
        let input = Darwin.open(source.path, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
        guard input >= 0 else { throw posixFileError(path: source.path) }
        defer { Darwin.close(input) }
        var initial = stat()
        guard fstat(input, &initial) == 0,
              (initial.st_mode & S_IFMT) == S_IFREG,
              initial.st_size >= 0 else {
            throw CocoaError(.fileReadUnsupportedScheme, userInfo: [NSFilePathErrorKey: source.path])
        }

        if try !isFilesystemCompressed(
            descriptor: input,
            metadata: initial,
            path: source.path
        ) {
            if try cloneFileContents(
                input: input,
                source: source,
                initial: initial,
                destination: destination
            ) {
                return .copyOnWriteClone
            }
        }

        let output = Darwin.open(
            destination.path,
            O_WRONLY | O_CREAT | O_EXCL | O_CLOEXEC,
            S_IRUSR | S_IWUSR
        )
        guard output >= 0 else { throw posixFileError(path: destination.path) }
        defer { Darwin.close(output) }
        do {
            var consumed: Int64 = 0
            var buffer = [UInt8](repeating: 0, count: 1_048_576)
            while true {
                try Task.checkCancellation()
                let count = buffer.withUnsafeMutableBytes { bytes in
                    Darwin.read(input, bytes.baseAddress, bytes.count)
                }
                if count < 0 && errno == EINTR { continue }
                guard count >= 0 else { throw posixFileError(path: source.path) }
                if count == 0 { break }
                consumed += Int64(count)
                var written = 0
                while written < count {
                    try Task.checkCancellation()
                    let result = buffer.withUnsafeBytes { bytes in
                        Darwin.write(output, bytes.baseAddress?.advanced(by: written), count - written)
                    }
                    if result < 0 && errno == EINTR { continue }
                    guard result > 0 else { throw posixFileError(path: destination.path) }
                    written += result
                }
            }
            try Task.checkCancellation()
            guard Darwin.fsync(output) == 0 else { throw posixFileError(path: destination.path) }
            var final = stat()
            var copied = stat()
            guard fstat(input, &final) == 0,
                  fstat(output, &copied) == 0,
                  final.st_dev == initial.st_dev,
                  final.st_ino == initial.st_ino,
                  final.st_size == initial.st_size,
                  final.st_mtimespec.tv_sec == initial.st_mtimespec.tv_sec,
                  final.st_mtimespec.tv_nsec == initial.st_mtimespec.tv_nsec,
                  consumed == initial.st_size,
                  (copied.st_mode & S_IFMT) == S_IFREG,
                  copied.st_nlink == 1,
                  copied.st_size == initial.st_size,
                  copied.st_mode & mode_t(0o7777) == mode_t(S_IRUSR | S_IWUSR),
                  copied.st_flags & UInt32(UF_COMPRESSED) == 0 else {
                throw CocoaError(.fileReadUnknown, userInfo: [NSFilePathErrorKey: source.path])
            }
            return .streamed
        } catch {
            try? fm.removeItem(at: destination)
            throw error
        }
    }

    private func cloneFileContents(
        input: Int32,
        source: URL,
        initial: stat,
        destination: URL
    ) throws -> Bool {
        let fm = FileManager.default
        let destinationParent = destination.deletingLastPathComponent()
        let parent = Darwin.open(
            destinationParent.path,
            O_RDONLY | O_DIRECTORY | O_NOFOLLOW | O_CLOEXEC
        )
        guard parent >= 0 else { throw posixFileError(path: destinationParent.path) }
        defer { Darwin.close(parent) }

        let result = destination.lastPathComponent.withCString {
            fclonefileat(input, parent, $0, UInt32(CLONE_NOOWNERCOPY))
        }
        if result != 0 {
            let cloneError = errno
            if fm.fileExists(atPath: destination.path)
                || ((try? fm.destinationOfSymbolicLink(atPath: destination.path)) != nil) {
                try? fm.removeItem(at: destination)
            }
            guard Self.shouldFallBackFromCloneError(cloneError) else {
                errno = cloneError
                throw posixFileError(path: destination.path)
            }
            return false
        }

        do {
            try Task.checkCancellation()
            let cloned = Darwin.open(
                destination.path,
                O_RDONLY | O_NOFOLLOW | O_CLOEXEC
            )
            guard cloned >= 0 else { throw posixFileError(path: destination.path) }
            defer { Darwin.close(cloned) }
            var cloneMetadata = stat()
            guard fstat(cloned, &cloneMetadata) == 0,
                  (cloneMetadata.st_mode & S_IFMT) == S_IFREG,
                  cloneMetadata.st_nlink == 1,
                  cloneMetadata.st_size == initial.st_size,
                  cloneMetadata.st_ino != initial.st_ino else {
                throw CocoaError(
                    .fileWriteUnknown,
                    userInfo: [NSFilePathErrorKey: destination.path]
                )
            }
            if try isFilesystemCompressed(
                descriptor: cloned,
                metadata: cloneMetadata,
                path: destination.path
            ) {
                try fm.removeItem(at: destination)
                return false
            }
            guard fchflags(cloned, 0) == 0,
                  fchmod(cloned, S_IRUSR | S_IWUSR) == 0 else {
                throw posixFileError(path: destination.path)
            }
            try removeExtendedAttributes(from: cloned, path: destination.path)
            guard Darwin.fsync(cloned) == 0 else {
                throw posixFileError(path: destination.path)
            }
            var sanitized = stat()
            guard fstat(cloned, &sanitized) == 0,
                  (sanitized.st_mode & S_IFMT) == S_IFREG,
                  sanitized.st_nlink == 1,
                  sanitized.st_size == initial.st_size,
                  sanitized.st_ino == cloneMetadata.st_ino,
                  sanitized.st_mode & mode_t(0o7777) == mode_t(S_IRUSR | S_IWUSR),
                  sanitized.st_flags & UInt32(UF_COMPRESSED) == 0 else {
                throw CocoaError(
                    .fileWriteUnknown,
                    userInfo: [NSFilePathErrorKey: destination.path]
                )
            }
            try validateUnchangedSource(input: input, source: source, initial: initial)
            return true
        } catch {
            try? fm.removeItem(at: destination)
            throw error
        }
    }

    private func isFilesystemCompressed(
        descriptor: Int32,
        metadata: stat,
        path: String
    ) throws -> Bool {
        if metadata.st_flags & UInt32(UF_COMPRESSED) != 0 {
            return true
        }
        let result = "com.apple.decmpfs".withCString { name in
            fgetxattr(descriptor, name, nil, 0, 0, 0)
        }
        if result >= 0 {
            return true
        }
        guard errno == ENOATTR else {
            throw posixFileError(path: path)
        }
        return false
    }

    private func removeExtendedAttributes(from descriptor: Int32, path: String) throws {
        let length = flistxattr(descriptor, nil, 0, 0)
        guard length >= 0 else { throw posixFileError(path: path) }
        guard length > 0 else { return }
        var names = [CChar](repeating: 0, count: length)
        let count = names.withUnsafeMutableBufferPointer {
            flistxattr(descriptor, $0.baseAddress, $0.count, 0)
        }
        guard count >= 0, count <= names.count else {
            throw posixFileError(path: path)
        }
        var removalError: Int32?
        names.withUnsafeBufferPointer { buffer in
            guard let base = buffer.baseAddress else { return }
            var offset = 0
            while offset < count {
                let name = base.advanced(by: offset)
                let nameLength = strlen(name)
                guard nameLength > 0, offset + nameLength < count else {
                    removalError = EINVAL
                    return
                }
                if fremovexattr(descriptor, name, 0) != 0, errno != ENOATTR {
                    removalError = errno
                    return
                }
                offset += nameLength + 1
            }
        }
        if let removalError {
            errno = removalError
            throw posixFileError(path: path)
        }
    }

    private func validateUnchangedSource(
        input: Int32,
        source: URL,
        initial: stat
    ) throws {
        var final = stat()
        guard fstat(input, &final) == 0,
              final.st_dev == initial.st_dev,
              final.st_ino == initial.st_ino,
              final.st_size == initial.st_size,
              final.st_mtimespec.tv_sec == initial.st_mtimespec.tv_sec,
              final.st_mtimespec.tv_nsec == initial.st_mtimespec.tv_nsec else {
            throw CocoaError(
                .fileReadUnknown,
                userInfo: [NSFilePathErrorKey: source.path]
            )
        }
    }

    private func posixFileError(path: String) -> NSError {
        NSError(
            domain: NSPOSIXErrorDomain,
            code: Int(errno),
            userInfo: [NSFilePathErrorKey: path]
        )
    }

    func rawFramesDirectory(index: Int, paths: ProjectPaths) -> URL {
        paths.framesRawURL.appendingPathComponent(String(format: "video_%03d", index), isDirectory: true)
    }

    func loadImages(in directory: URL) throws -> [URL] {
        let fm = FileManager.default
        guard fm.fileExists(atPath: directory.path) else { return [] }
        return try fm.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)
            .filter { !$0.hasDirectoryPath }
            .filter { supportedImageExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    func loadPhotos(in directory: URL) throws -> [URL] {
        guard FileManager.default.fileExists(atPath: directory.path) else { return [] }
        return try PhotoInputPreflight.discoveredPhotos(in: directory)
    }

    struct ValidPhotoFilterResult: Sendable {
        let frames: [URL]
        let unreadableCount: Int
        let duplicateCount: Int
    }

    /// Rejects files that merely have an image extension and exact byte-for-byte duplicates.
    /// Selection policy runs only after this validity boundary, including "Use all valid photos."
    func filterValidUniquePhotos(_ photos: [URL]) throws -> ValidPhotoFilterResult {
        let inspection = try PhotoInputPreflight.inspect(photos)

        return ValidPhotoFilterResult(
            frames: inspection.validPhotos,
            unreadableCount: inspection.summary.unreadablePhotoCount,
            duplicateCount: inspection.summary.duplicatePhotoCount
        )
    }

    func applyFrameBudget(
        to groups: [SelectedFrameGroup],
        targetCount: Int,
        photoSelection: PhotoSelection = .automatic
    ) throws -> [SelectedFrameGroup] {
        let targets = try resolveGroupTargetCounts(
            capacities: groups.map { $0.frames.count },
            isVideo: groups.map(\.isVideo),
            targetCount: targetCount,
            photoSelection: photoSelection
        )
        return zip(groups, targets).compactMap { group, count in
            guard count > 0 else { return nil }
            return SelectedFrameGroup(
                id: group.id,
                frames: evenlySpacedFrames(group.frames, targetCount: count),
                isVideo: group.isVideo
            )
        }
    }

    func resolveGlobalFrameTargets(
        videos: [VideoFrameAllocationInput],
        validPhotoCount: Int,
        targetCount: Int,
        photoSelection: PhotoSelection
    ) throws -> GlobalFrameTargets {
        guard validPhotoCount >= 0 else { throw PipelineError.invalidInput }
        let virtualVideoCapacities = try allocateRequiredVideoFrameTargets(
            videos,
            totalTargetCount: targetCount
        )
        var capacities = virtualVideoCapacities
        var videoFlags = [Bool](repeating: true, count: videos.count)
        if validPhotoCount > 0 {
            capacities.append(validPhotoCount)
            videoFlags.append(false)
        }
        let targets = try resolveGroupTargetCounts(
            capacities: capacities,
            isVideo: videoFlags,
            targetCount: targetCount,
            photoSelection: photoSelection
        )
        return GlobalFrameTargets(
            videoTargets: Array(targets.prefix(videos.count)),
            photoTarget: validPhotoCount > 0 ? targets.last ?? 0 : 0
        )
    }

    private func resolveGroupTargetCounts(
        capacities: [Int],
        isVideo: [Bool],
        targetCount: Int,
        photoSelection: PhotoSelection
    ) throws -> [Int] {
        guard capacities.count == isVideo.count,
              capacities.allSatisfy({ $0 >= 0 }) else {
            throw PipelineError.invalidInput
        }
        guard photoSelection == .useAllValidPhotos else {
            return try resolveNormalGroupTargetCounts(
                capacities: capacities,
                isVideo: isVideo,
                targetCount: targetCount
            )
        }

        let videoIndices = capacities.indices.filter { isVideo[$0] }
        let photoCount = capacities.indices
            .filter { !isVideo[$0] }
            .reduce(0) { $0 + capacities[$1] }
        let availableVideoCount = videoIndices.reduce(0) { $0 + capacities[$1] }
        let reservedVideoCount = min(
            availableVideoCount,
            RunPlanResolver.minimumReservedVideoFrameCount(
                keyframeBudget: targetCount,
                videoCount: videoIndices.count
            )
        )
        let maximumPhotoCount = max(0, targetCount - reservedVideoCount)
        guard photoCount <= maximumPhotoCount else {
            throw PipelineError.photoSelectionExceedsBudget(
                selected: photoCount,
                maximum: maximumPhotoCount
            )
        }
        let videoTargets = try resolveNormalGroupTargetCounts(
            capacities: videoIndices.map { capacities[$0] },
            isVideo: [Bool](repeating: true, count: videoIndices.count),
            targetCount: max(0, targetCount - photoCount)
        )
        var result = capacities.indices.map { isVideo[$0] ? 0 : capacities[$0] }
        for (offset, index) in videoIndices.enumerated() {
            result[index] = videoTargets[offset]
        }
        return result
    }

    private func resolveNormalGroupTargetCounts(
        capacities: [Int],
        isVideo: [Bool],
        targetCount: Int
    ) throws -> [Int] {
        guard targetCount > 0 else {
            return [Int](repeating: 0, count: capacities.count)
        }
        let total = capacities.reduce(0, +)
        guard total > targetCount else { return capacities }

        var targets = capacities.indices.map { index in
            isVideo[index] ? min(2, capacities[index]) : 0
        }
        let requiredVideoCoverage = targets.reduce(0, +)
        guard requiredVideoCoverage <= targetCount else {
            throw PipelineError.videoFrameBudgetTooSmall(
                required: requiredVideoCoverage,
                available: targetCount
            )
        }
        let residualCapacities = zip(capacities, targets).map { capacity, target in
            capacity - target
        }
        let extras = allocateProportionally(
            weights: residualCapacities.map(Double.init),
            capacities: residualCapacities,
            totalCount: targetCount - requiredVideoCoverage
        )
        for index in targets.indices {
            targets[index] += extras[index]
        }
        return targets
    }

    func evenlySpacedFrames(_ frames: [URL], targetCount: Int) -> [URL] {
        guard targetCount > 0, !frames.isEmpty else { return [] }
        guard frames.count > targetCount else { return frames }
        guard targetCount > 1 else { return [frames[frames.count / 2]] }
        let step = Double(frames.count - 1) / Double(targetCount - 1)
        return (0..<targetCount).map { index in
            frames[Int((Double(index) * step).rounded())]
        }
    }

    func allocateVideoFrameTargets(
        _ inputs: [VideoFrameAllocationInput],
        totalTargetCount: Int
    ) throws -> [Int] {
        guard totalTargetCount > 0 else {
            return [Int](repeating: 0, count: inputs.count)
        }
        for (index, input) in inputs.enumerated() {
            guard input.availableCandidateCount >= 0,
                  input.availableCandidateCount == 0
                    || (input.durationSeconds.isFinite && input.durationSeconds > 0) else {
                throw VideoFrameAllocationError.invalidInput(index: index)
            }
        }

        let capacities = inputs.map(\.availableCandidateCount)
        let effectiveBudget = min(totalTargetCount, capacities.reduce(0, +))
        var allocations = capacities.map { min(2, $0) }
        let requiredCoverage = allocations.reduce(0, +)
        guard effectiveBudget >= requiredCoverage else {
            throw VideoFrameAllocationError.insufficientBudgetForClipCoverage(
                required: requiredCoverage,
                available: effectiveBudget
            )
        }

        let residualCapacities = zip(capacities, allocations).map { $0 - $1 }
        let extras = allocateProportionally(
            weights: inputs.map(\.durationSeconds),
            capacities: residualCapacities,
            totalCount: effectiveBudget - requiredCoverage
        )
        for index in allocations.indices {
            allocations[index] += extras[index]
        }
        return allocations
    }

    func allocateRequiredVideoFrameTargets(
        _ inputs: [VideoFrameAllocationInput],
        totalTargetCount: Int
    ) throws -> [Int] {
        do {
            return try allocateVideoFrameTargets(
                inputs,
                totalTargetCount: totalTargetCount
            )
        } catch let error as VideoFrameAllocationError {
            switch error {
            case .invalidInput:
                throw PipelineError.invalidInput
            case let .insufficientBudgetForClipCoverage(required, available):
                throw PipelineError.videoFrameBudgetTooSmall(
                    required: required,
                    available: available
                )
            }
        }
    }

    private func allocateProportionally(
        weights: [Double],
        capacities: [Int],
        totalCount: Int
    ) -> [Int] {
        precondition(weights.count == capacities.count)
        let effectiveTotal = min(max(0, totalCount), capacities.reduce(0, +))
        var allocations = [Int](repeating: 0, count: capacities.count)
        var remaining = effectiveTotal
        var active = capacities.indices.filter {
            capacities[$0] > 0 && weights[$0].isFinite && weights[$0] > 0
        }

        while remaining > 0, !active.isEmpty {
            let totalWeight = active.reduce(0.0) { $0 + weights[$1] }
            let ideals = Dictionary(uniqueKeysWithValues: active.map { index in
                (index, Double(remaining) * weights[index] / totalWeight)
            })
            let saturated = active.filter { index in
                Double(capacities[index] - allocations[index]) <= (ideals[index] ?? 0)
            }
            if !saturated.isEmpty {
                for index in saturated.sorted() {
                    let available = capacities[index] - allocations[index]
                    allocations[index] += available
                    remaining -= available
                }
                let saturatedSet = Set(saturated)
                active.removeAll { saturatedSet.contains($0) }
                continue
            }

            var remainders: [(index: Int, fraction: Double)] = []
            for index in active {
                let ideal = ideals[index] ?? 0
                let whole = min(
                    capacities[index] - allocations[index],
                    Int(floor(ideal))
                )
                allocations[index] += whole
                remaining -= whole
                remainders.append((index, ideal - floor(ideal)))
            }
            remainders.sort {
                $0.fraction == $1.fraction
                    ? $0.index < $1.index
                    : $0.fraction > $1.fraction
            }
            for remainder in remainders where remaining > 0 {
                guard allocations[remainder.index] < capacities[remainder.index] else {
                    continue
                }
                allocations[remainder.index] += 1
                remaining -= 1
            }
        }
        return allocations
    }

    func persistCheckpoint(
        paths: ProjectPaths,
        stage: PipelineStage,
        progress: Double? = nil,
        message: String? = nil,
        details: PipelineCheckpointDetails? = nil
    ) {
        guard var metadata = try? ProjectMetadataStore.load(from: paths.metadataURL) else { return }
        metadata.checkpoint = PipelineCheckpoint(
            stage: stage,
            updatedAt: Date(),
            progressFraction: progress,
            message: message,
            details: details
        )
        // Use the notes-preserving save so a checkpoint written mid-run cannot clobber a note
        // the user edited since this metadata was loaded, matching every other in-run write.
        try? ProjectMetadataStore.savePreservingUserEditableFields(metadata, to: paths.metadataURL)
    }

    struct FrameExtractionProfile {
        let targetCount: Int
        let maxDimension: CGFloat
        let targetFPS: Int
        let minDistanceRatio: Double
        let outputFormat: FrameOutputFormat
    }

    func frameExtractionProfile(for plan: ResolvedRunPlan, detail: DetailProfile) -> FrameExtractionProfile {
        let minDistanceRatio: Double = switch plan.capturePath {
        case .orbit: 0.12
        case .automatic, .walkthrough: 0.20
        case .largeArea: 0.30
        }
        return FrameExtractionProfile(
            targetCount: plan.keyframeBudget,
            maxDimension: CGFloat(plan.maximumImageDimension),
            targetFPS: plan.analysisFrameRate,
            minDistanceRatio: minDistanceRatio,
            outputFormat: detail == .highDetail ? .png : .jpeg
        )
    }

    func cameraModel(
        detailProfile: DetailProfile,
        capturePath: CapturePath,
        lensProjection: LensProjection = .automatic
    ) -> String {
        switch lensProjection {
        case .fisheye:
            return "OPENCV_FISHEYE"
        case .perspective:
            return detailProfile == .highDetail ? "OPENCV" : "SIMPLE_RADIAL"
        case .automatic:
            break
        }
        if detailProfile == .highDetail,
           capturePath == .walkthrough || capturePath == .largeArea {
            return "OPENCV"
        }
        return "SIMPLE_RADIAL"
    }

    func shouldUseSequential(
        selectedFrames: [URL],
        input: InputSpec,
        forceExhaustive: Bool,
        pairingPolicy: ResolvedPairingPolicy? = nil
    ) -> Bool {
        if forceExhaustive { return false }
        if let pairingPolicy {
            guard pairingPolicy != .unorderedRetrieval else { return false }
            return selectedFrames.count >= 30
        }
        guard input.hasVideos, !input.hasPhotos else { return false }
        guard input.videoFiles.count == 1 else { return false }
        if selectedFrames.count < 30 { return false }
        return true
    }
}
