import CoreGraphics
import CoreImage
import Darwin
import Foundation
import ImageIO
import UniformTypeIdentifiers

extension PipelineRunner {
    // Selected-frame names and group identifiers are generated by EasySplat. Four
    // MiB allows more than one KiB per entry at the 3,000-frame release boundary.
    private static let maximumSelectedFrameManifestBytes = 4 * 1_024 * 1_024

    struct SelectedFrameGroup: Sendable {
        let id: String
        let frames: [URL]
        let isVideo: Bool
    }

    struct SelectedFrameMapping: Codable, Sendable {
        let outputFileName: String
        let groupId: String
        let isVideo: Bool
        let timestampSeconds: Double?
        let lowLightExposureEV: Double?

        init(
            outputFileName: String,
            groupId: String,
            isVideo: Bool,
            timestampSeconds: Double? = nil,
            lowLightExposureEV: Double? = nil
        ) {
            self.outputFileName = outputFileName
            self.groupId = groupId
            self.isVideo = isVideo
            self.timestampSeconds = timestampSeconds
            self.lowLightExposureEV = lowLightExposureEV
        }
    }

    var supportedImageExtensions: Set<String> {
        PhotoInputPreflight.supportedExtensions
    }

    func isHeicImage(_ url: URL) -> Bool {
        let ext = url.pathExtension.lowercased()
        return ext == "heic" || ext == "heif"
    }

    func selectedImagesHaveUniformPixelDimensions(_ images: [URL]) throws -> Bool {
        var expectedDimensions: (width: Int, height: Int)?
        for image in images {
            guard let source = CGImageSourceCreateWithURL(image as CFURL, nil),
                  let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil)
                    as? [CFString: Any],
                  let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
                  let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
                  width > 0,
                  height > 0 else {
                throw PipelineError.imageTranscodeFailed(
                    "Failed to inspect selected image: \(image.lastPathComponent)"
                )
            }
            let dimensions = (width: width, height: height)
            if let expectedDimensions,
               expectedDimensions.width != dimensions.width
                || expectedDimensions.height != dimensions.height {
                return false
            }
            expectedDimensions = dimensions
        }
        return expectedDimensions != nil
    }

    func transcodeHeicToJpeg(source: URL, destination: URL) throws {
        guard let sourceRef = CGImageSourceCreateWithURL(source as CFURL, nil) else {
            throw PipelineError.imageTranscodeFailed("Failed to read HEIC image: \(source.lastPathComponent)")
        }

        let props = CGImageSourceCopyPropertiesAtIndex(sourceRef, 0, nil) as? [CFString: Any]
        let width = (props?[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue ?? 0
        let height = (props?[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue ?? 0
        let maxDim = max(1, max(width, height))
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxDim,
            kCGImageSourceShouldCache: false
        ]

        guard let cgImage = CGImageSourceCreateThumbnailAtIndex(sourceRef, 0, options as CFDictionary) else {
            throw PipelineError.imageTranscodeFailed("Failed to decode HEIC image: \(source.lastPathComponent)")
        }

        guard let destRef = CGImageDestinationCreateWithURL(destination as CFURL, UTType.jpeg.identifier as CFString, 1, nil) else {
            throw PipelineError.imageTranscodeFailed("Failed to create JPEG output: \(destination.lastPathComponent)")
        }

        let destOptions: [CFString: Any] = [
            kCGImageDestinationLossyCompressionQuality: 0.95
        ]
        CGImageDestinationAddImage(destRef, cgImage, destOptions as CFDictionary)
        guard CGImageDestinationFinalize(destRef) else {
            throw PipelineError.imageTranscodeFailed("Failed to write JPEG image: \(destination.lastPathComponent)")
        }
    }

    // Earlier versions copied HEIC photos into Selected/ directly. Geometry tools expect
    // JPEG or PNG, so resumed projects transcode those files in place.
    func normalizeSelectedImagesForTooling(paths: ProjectPaths) throws -> Int {
        let fm = FileManager.default
        guard fm.fileExists(atPath: paths.framesSelectedURL.path) else { return 0 }

        let files = try fm.contentsOfDirectory(at: paths.framesSelectedURL, includingPropertiesForKeys: nil)
            .filter { !$0.hasDirectoryPath }

        var renamed: [String: String] = [:]
        var converted = 0
        for file in files where isHeicImage(file) {
            let newName = file.deletingPathExtension().lastPathComponent + ".jpg"
            let dest = paths.framesSelectedURL.appendingPathComponent(newName)

            if !fm.fileExists(atPath: dest.path) {
                try transcodeHeicToJpeg(source: file, destination: dest)
            }
            // Ensure downstream tools don't see a mix of formats with duplicate basenames.
            try? fm.removeItem(at: file)
            renamed[file.lastPathComponent] = newName
            converted += 1
        }

        if converted > 0,
           fm.fileExists(atPath: paths.framesSelectedManifestURL.path),
           let manifest = try? loadSelectedFrameManifest(from: paths.framesSelectedManifestURL) {
            let updated = manifest.map { entry in
                guard let newName = renamed[entry.outputFileName] else { return entry }
                return SelectedFrameMapping(
                    outputFileName: newName,
                    groupId: entry.groupId,
                    isVideo: entry.isVideo,
                    timestampSeconds: entry.timestampSeconds,
                    lowLightExposureEV: entry.lowLightExposureEV
                )
            }
            try saveSelectedFrameManifest(updated, to: paths.framesSelectedManifestURL)
        }

        return converted
    }

    func downsampleFrames(_ frames: [URL], targetCount: Int) -> [URL] {
        guard !frames.isEmpty else { return [] }
        guard targetCount > 0 else { return [] }
        if targetCount == 1 {
            return [frames[frames.count / 2]]
        }
        if frames.count <= targetCount {
            return frames
        }
        let step = Double(frames.count - 1) / Double(targetCount - 1)
        return (0..<targetCount).map { index in
            let position = Int(round(Double(index) * step))
            return frames[position]
        }
    }

    func downsampleSelectedFrames(to targetCount: Int, paths: ProjectPaths) throws -> [URL]? {
        guard targetCount > 0 else { return nil }
        let existing = try loadImages(in: paths.framesSelectedURL)
        guard existing.count > targetCount else { return nil }
        let reduced = downsampleFrames(existing, targetCount: targetCount)

        let tempSelected = paths.framesSelectedURL.deletingLastPathComponent()
            .appendingPathComponent("selected_retry", isDirectory: true)
        try resetDirectory(tempSelected)
        let newSelection = try copySelected(reduced, to: tempSelected)
        removeIfExists(paths.framesSelectedURL)
        try FileManager.default.moveItem(at: tempSelected, to: paths.framesSelectedURL)
        if FileManager.default.fileExists(atPath: paths.framesSelectedManifestURL.path),
           let manifest = try? loadSelectedFrameManifest(from: paths.framesSelectedManifestURL) {
            let manifestByFile = Dictionary(manifest.map { ($0.outputFileName, $0) }, uniquingKeysWith: { first, _ in first })
            var updated: [SelectedFrameMapping] = []
            updated.reserveCapacity(newSelection.count)
            for (index, original) in reduced.enumerated() where index < newSelection.count {
                let oldName = original.lastPathComponent
                guard let entry = manifestByFile[oldName] else { continue }
                let newName = newSelection[index].lastPathComponent
                updated.append(SelectedFrameMapping(
                    outputFileName: newName,
                    groupId: entry.groupId,
                    isVideo: entry.isVideo,
                    timestampSeconds: entry.timestampSeconds,
                    lowLightExposureEV: entry.lowLightExposureEV
                ))
            }
            try? saveSelectedFrameManifest(updated, to: paths.framesSelectedManifestURL)
        }
        return try loadImages(in: paths.framesSelectedURL)
    }

    func copySelected(
        groups: [SelectedFrameGroup],
        to directory: URL,
        manifestURL: URL,
        maxDimension: CGFloat,
        progress: ((Double, String) -> Void)? = nil
    ) throws -> (frames: [URL], manifest: [SelectedFrameMapping]) {
        let fm = FileManager.default
        var output: [URL] = []
        var manifest: [SelectedFrameMapping] = []
        let total = groups.reduce(0) { $0 + $1.frames.count }
        var index = 0
        var copied = 0
        var lowLightContext: CIContext?
        for group in groups {
            for frame in group.frames {
                try Task.checkCancellation()
                let sourceExt = frame.pathExtension.lowercased()
                let destExt: String = {
                    if sourceExt.isEmpty { return "jpg" }
                    if sourceExt == "heic" || sourceExt == "heif" { return "jpg" }
                    return sourceExt
                }()
                let dest = directory.appendingPathComponent(String(format: "frame_%06d.%@", index, destExt))
                if fm.fileExists(atPath: dest.path) { try fm.removeItem(at: dest) }
                let lowLightExposureEV = try copySelectedFrame(
                    source: frame,
                    destination: dest,
                    maxDimension: maxDimension,
                    context: &lowLightContext
                )
                output.append(dest)
                manifest.append(SelectedFrameMapping(
                    outputFileName: dest.lastPathComponent,
                    groupId: group.id,
                    isVideo: group.isVideo,
                    timestampSeconds: group.isVideo
                        ? FrameExtractor.timestampSeconds(from: frame.lastPathComponent)
                        : nil,
                    lowLightExposureEV: lowLightExposureEV
                ))
                index += 1
                copied += 1
                if let progress, total > 0, copied % 5 == 0 || copied == total {
                    let fraction = Double(copied) / Double(total)
                    progress(fraction, "Copying selected frames \(copied)/\(total)")
                }
            }
        }
        try saveSelectedFrameManifest(manifest, to: manifestURL)
        return (output, manifest)
    }

    private func copySelectedFrame(
        source: URL,
        destination: URL,
        maxDimension: CGFloat,
        context: inout CIContext?
    ) throws -> Double? {
        let exposureEV = (try? FrameScoring.scoreFrame(at: source).lowLightExposureEV) ?? 0
        guard let sourceRef = CGImageSourceCreateWithURL(source as CFURL, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(sourceRef, 0, nil) as? [CFString: Any],
              let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
              width > 0,
              height > 0 else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to inspect selected image: \(source.lastPathComponent)"
            )
        }
        let largestDimension = max(width, height)
        let boundedDimension: Int
        if maxDimension.isFinite, maxDimension > 0 {
            let clampedDimension = min(CGFloat(largestDimension), maxDimension.rounded(.down))
            boundedDimension = max(1, Int(clampedDimension))
        } else {
            boundedDimension = largestDimension
        }
        let needsTranscode = exposureEV > 0
            || isHeicImage(source)
            || largestDimension > boundedDimension
        guard needsTranscode else {
            try FileManager.default.copyItem(at: source, to: destination)
            return nil
        }

        try Task.checkCancellation()
        guard let image = CGImageSourceCreateThumbnailAtIndex(
                sourceRef,
                0,
                [
                    kCGImageSourceCreateThumbnailFromImageAlways: true,
                    kCGImageSourceCreateThumbnailWithTransform: true,
                    kCGImageSourceThumbnailMaxPixelSize: boundedDimension,
                    kCGImageSourceShouldCache: false,
                ] as CFDictionary
              ) else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to decode selected image: \(source.lastPathComponent)"
            )
        }
        try Task.checkCancellation()

        let outputImage: CGImage
        if exposureEV > 0 {
            let input = CIImage(cgImage: image)
            let adjusted = input.applyingFilter(
                "CIExposureAdjust",
                parameters: [kCIInputEVKey: exposureEV]
            )
            let renderingContext = context ?? CIContext(options: [.cacheIntermediates: false])
            context = renderingContext
            guard let adjustedImage = renderingContext.createCGImage(adjusted, from: input.extent) else {
                throw PipelineError.imageTranscodeFailed(
                    "Failed to adjust low-light image: \(source.lastPathComponent)"
                )
            }
            outputImage = adjustedImage
        } else {
            outputImage = image
        }

        let outputType: UTType = destination.pathExtension.lowercased() == "png" ? .png : .jpeg
        guard let destinationRef = CGImageDestinationCreateWithURL(
            destination as CFURL,
            outputType.identifier as CFString,
            1,
            nil
        ) else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to create selected image: \(destination.lastPathComponent)"
            )
        }
        let options: [CFString: Any] = outputType == .jpeg
            ? [kCGImageDestinationLossyCompressionQuality: 0.95]
            : [:]
        CGImageDestinationAddImage(destinationRef, outputImage, options as CFDictionary)
        guard CGImageDestinationFinalize(destinationRef) else {
            throw PipelineError.imageTranscodeFailed(
                "Failed to write selected image: \(destination.lastPathComponent)"
            )
        }
        return exposureEV > 0 ? exposureEV : nil
    }

    func saveSelectedFrameManifest(_ manifest: [SelectedFrameMapping], to url: URL) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(manifest)
        try data.write(to: url, options: [.atomic])
    }

    func loadSelectedFrameManifest(from url: URL) throws -> [SelectedFrameMapping] {
        let data = try BoundedFileReader.readRegularFile(
            at: url,
            maximumBytes: Self.maximumSelectedFrameManifestBytes
        )
        return try JSONDecoder().decode([SelectedFrameMapping].self, from: data)
    }

    func importedVideoURLs(for videoFiles: [String], paths: ProjectPaths) -> [URL] {
        var usedNames = Set<String>()
        return videoFiles.map { file in
            let source = URL(fileURLWithPath: file)
            let name = uniqueImportedVideoName(for: source, usedNames: &usedNames)
            return paths.originalsURL.appendingPathComponent(name)
        }
    }

    private func uniqueImportedVideoName(for source: URL, usedNames: inout Set<String>) -> String {
        let filename = source.lastPathComponent
        if usedNames.insert(filename.lowercased()).inserted {
            return filename
        }

        let nsName = filename as NSString
        let stem = nsName.deletingPathExtension
        let ext = nsName.pathExtension
        var suffix = 2
        while true {
            let candidate: String
            if ext.isEmpty {
                candidate = "\(stem)-\(suffix)"
            } else {
                candidate = "\(stem)-\(suffix).\(ext)"
            }
            if usedNames.insert(candidate.lowercased()).inserted {
                return candidate
            }
            suffix += 1
        }
    }

    func importInputs(
        metadata: ProjectMetadata,
        paths: ProjectPaths,
        progress: (Double, String) -> Void
    ) throws {
        var tasks: [(label: String, action: () throws -> Void)] = []

        let importedVideos = importedVideoURLs(for: metadata.input.videoFiles, paths: paths)
        for (file, dest) in zip(metadata.input.videoFiles, importedVideos) {
            let source = URL(fileURLWithPath: file)
            tasks.append((label: dest.lastPathComponent, action: {
                if try self.importedVideoNeedsCopy(dest) {
                    try self.copyFileAtomically(from: source, to: dest)
                }
            }))
        }

        if let photosFolder = metadata.input.photosFolder {
            let sourceFolder = URL(fileURLWithPath: photosFolder)
            let dest = paths.importedPhotosURL
            tasks.append((label: "Photos: \(sourceFolder.lastPathComponent)", action: {
                let photos = try PhotoInputPreflight.discoveredPhotos(in: sourceFolder)
                let inspection = try PhotoInputPreflight.inspect(photos)
                guard !inspection.validPhotos.isEmpty else {
                    throw PipelineError.invalidInput
                }
                let entries = self.importedPhotoEntries(for: inspection.validPhotos)
                if try self.importedPhotoFolderNeedsCopy(entries: entries, destination: dest) {
                    try self.copyValidPhotosAtomically(entries, to: dest)
                }
            }))
        }

        guard !tasks.isEmpty else { return }
        let total = tasks.count
        for (index, task) in tasks.enumerated() {
            try Task.checkCancellation()
            let message = "Copying input \(index + 1)/\(total): \(task.label)"
            let startFraction = Double(index) / Double(total)
            progress(startFraction, message)
            try task.action()
            let endFraction = Double(index + 1) / Double(total)
            progress(endFraction, message)
        }
    }

    func copySelected(_ frames: [URL], to directory: URL) throws -> [URL] {
        let fm = FileManager.default
        var output: [URL] = []
        for (index, url) in frames.enumerated() {
            try Task.checkCancellation()
            let sourceExt = url.pathExtension.lowercased()
            let destExt: String = {
                if sourceExt.isEmpty { return "jpg" }
                if sourceExt == "heic" || sourceExt == "heif" { return "jpg" }
                return sourceExt
            }()
            let dest = directory.appendingPathComponent(String(format: "frame_%06d.%@", index, destExt))
            if fm.fileExists(atPath: dest.path) { try fm.removeItem(at: dest) }
            if isHeicImage(url) {
                try transcodeHeicToJpeg(source: url, destination: dest)
            } else {
                try fm.copyItem(at: url, to: dest)
            }
            output.append(dest)
        }
        return output
    }

    func importedVideoNeedsCopy(_ destination: URL) throws -> Bool {
        let fm = FileManager.default
        guard fm.fileExists(atPath: destination.path) else { return true }
        let size = (try? fm.attributesOfItem(atPath: destination.path)[.size] as? NSNumber)?.int64Value ?? 0
        return size <= 0
    }

    private func importedPhotoEntries(for photos: [URL]) -> [(source: URL, fileName: String)] {
        var usedNames = Set<String>()
        return photos.map { photo in
            let filename = uniqueImportedPhotoName(for: photo, usedNames: &usedNames)
            return (photo, filename)
        }
    }

    private func uniqueImportedPhotoName(for source: URL, usedNames: inout Set<String>) -> String {
        let filename = source.lastPathComponent
        if usedNames.insert(filename.lowercased()).inserted {
            return filename
        }

        let nsName = filename as NSString
        let stem = nsName.deletingPathExtension
        let ext = nsName.pathExtension
        var suffix = 2
        while true {
            let candidate = ext.isEmpty
                ? "\(stem)-\(suffix)"
                : "\(stem)-\(suffix).\(ext)"
            if usedNames.insert(candidate.lowercased()).inserted {
                return candidate
            }
            suffix += 1
        }
    }

    func importedPhotoFolderNeedsCopy(
        entries: [(source: URL, fileName: String)],
        destination: URL
    ) throws -> Bool {
        let fm = FileManager.default
        guard fm.fileExists(atPath: destination.path) else { return true }
        try Task.checkCancellation()
        let contents = try fm.contentsOfDirectory(
            at: destination,
            includingPropertiesForKeys: [.isRegularFileKey, .fileSizeKey],
            options: [.skipsHiddenFiles]
        )
        guard contents.count == entries.count else { return true }
        let expectedNames = Set(entries.map(\.fileName))
        guard Set(contents.map(\.lastPathComponent)) == expectedNames else { return true }
        for file in contents {
            try Task.checkCancellation()
            let values = try file.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
            if values.isRegularFile != true || (values.fileSize ?? 0) <= 0 {
                return true
            }
        }
        return false
    }

    func copyFileAtomically(from source: URL, to destination: URL) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        let temp = destination.deletingLastPathComponent()
            .appendingPathComponent(".\(destination.lastPathComponent).\(UUID().uuidString).tmp")
        defer {
            if fm.fileExists(atPath: temp.path) {
                try? fm.removeItem(at: temp)
            }
        }

        try copyFileContents(from: source, to: temp)
        try Task.checkCancellation()
        if fm.fileExists(atPath: destination.path) {
            _ = try fm.replaceItemAt(destination, withItemAt: temp, backupItemName: nil, options: [])
        } else {
            try fm.moveItem(at: temp, to: destination)
        }
    }

    private func copyValidPhotosAtomically(
        _ entries: [(source: URL, fileName: String)],
        to destination: URL
    ) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        let temp = destination.deletingLastPathComponent()
            .appendingPathComponent(".\(destination.lastPathComponent).\(UUID().uuidString).tmp", isDirectory: true)
        defer {
            if fm.fileExists(atPath: temp.path) {
                try? fm.removeItem(at: temp)
            }
        }

        try fm.createDirectory(at: temp, withIntermediateDirectories: false)
        for entry in entries {
            try Task.checkCancellation()
            try copyFileContents(
                from: entry.source,
                to: temp.appendingPathComponent(entry.fileName)
            )
        }
        try Task.checkCancellation()
        if fm.fileExists(atPath: destination.path) {
            _ = try fm.replaceItemAt(destination, withItemAt: temp, backupItemName: nil, options: [])
        } else {
            try fm.moveItem(at: temp, to: destination)
        }
    }

    private func copyFileContents(from source: URL, to destination: URL) throws {
        try Task.checkCancellation()
        let fm = FileManager.default
        let input = Darwin.open(source.path, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
        guard input >= 0 else { throw posixFileError(path: source.path) }
        defer { Darwin.close(input) }
        var initial = stat()
        guard fstat(input, &initial) == 0,
              (initial.st_mode & S_IFMT) == S_IFREG,
              initial.st_size >= 0 else {
            throw CocoaError(.fileReadUnsupportedScheme, userInfo: [NSFilePathErrorKey: source.path])
        }
        let output = Darwin.open(
            destination.path,
            O_WRONLY | O_CREAT | O_EXCL | O_CLOEXEC,
            S_IRUSR | S_IWUSR
        )
        guard output >= 0 else { throw posixFileError(path: destination.path) }
        defer { Darwin.close(output) }
        do {
            var consumed: Int64 = 0
            var buffer = [UInt8](repeating: 0, count: 1_048_576)
            while true {
                try Task.checkCancellation()
                let count = buffer.withUnsafeMutableBytes { bytes in
                    Darwin.read(input, bytes.baseAddress, bytes.count)
                }
                if count < 0 && errno == EINTR { continue }
                guard count >= 0 else { throw posixFileError(path: source.path) }
                if count == 0 { break }
                consumed += Int64(count)
                var written = 0
                while written < count {
                    try Task.checkCancellation()
                    let result = buffer.withUnsafeBytes { bytes in
                        Darwin.write(output, bytes.baseAddress?.advanced(by: written), count - written)
                    }
                    if result < 0 && errno == EINTR { continue }
                    guard result > 0 else { throw posixFileError(path: destination.path) }
                    written += result
                }
            }
            try Task.checkCancellation()
            guard Darwin.fsync(output) == 0 else { throw posixFileError(path: destination.path) }
            var final = stat()
            guard fstat(input, &final) == 0,
                  final.st_dev == initial.st_dev,
                  final.st_ino == initial.st_ino,
                  final.st_size == initial.st_size,
                  final.st_mtimespec.tv_sec == initial.st_mtimespec.tv_sec,
                  final.st_mtimespec.tv_nsec == initial.st_mtimespec.tv_nsec,
                  consumed == initial.st_size else {
                throw CocoaError(.fileReadUnknown, userInfo: [NSFilePathErrorKey: source.path])
            }
        } catch {
            try? fm.removeItem(at: destination)
            throw error
        }
    }

    private func posixFileError(path: String) -> NSError {
        NSError(
            domain: NSPOSIXErrorDomain,
            code: Int(errno),
            userInfo: [NSFilePathErrorKey: path]
        )
    }

    func rawFramesDirectory(index: Int, paths: ProjectPaths) -> URL {
        paths.framesRawURL.appendingPathComponent(String(format: "video_%03d", index), isDirectory: true)
    }

    func loadImages(in directory: URL) throws -> [URL] {
        let fm = FileManager.default
        guard fm.fileExists(atPath: directory.path) else { return [] }
        return try fm.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)
            .filter { !$0.hasDirectoryPath }
            .filter { supportedImageExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    func loadPhotos(in directory: URL) throws -> [URL] {
        guard FileManager.default.fileExists(atPath: directory.path) else { return [] }
        return try PhotoInputPreflight.discoveredPhotos(in: directory)
    }

    struct ValidPhotoFilterResult: Sendable {
        let frames: [URL]
        let unreadableCount: Int
        let duplicateCount: Int
    }

    /// Rejects files that merely have an image extension and exact byte-for-byte duplicates.
    /// Selection policy runs only after this validity boundary, including "Use all valid photos."
    func filterValidUniquePhotos(_ photos: [URL]) throws -> ValidPhotoFilterResult {
        let inspection = try PhotoInputPreflight.inspect(photos)

        return ValidPhotoFilterResult(
            frames: inspection.validPhotos,
            unreadableCount: inspection.summary.unreadablePhotoCount,
            duplicateCount: inspection.summary.duplicatePhotoCount
        )
    }

    struct BlurFilterResult: Sendable {
        let frames: [URL]
        let dropped: Int
    }

    func scoreSharpnessForFrames(
        _ frames: [URL],
        progress: (Double, String) -> Void
    ) throws -> [URL: Double] {
        guard !frames.isEmpty else { return [:] }
        let total = Double(frames.count)
        var results: [URL: Double] = [:]
        results.reserveCapacity(frames.count)
        for (index, url) in frames.enumerated() {
            try Task.checkCancellation()
            if let score = try? FrameScoring.scoreFrame(at: url) {
                results[url] = max(score.blurScore, score.laplacianScore)
            }
            if index % 10 == 0 || index + 1 == frames.count {
                let fraction = min(Double(index + 1) / total, 1.0)
                progress(fraction, "Analyzing frame sharpness")
            }
        }
        return results
    }

    func applyFrameBudget(
        to groups: [SelectedFrameGroup],
        targetCount: Int,
        photoSelection: PhotoSelection = .automatic
    ) throws -> [SelectedFrameGroup] {
        guard photoSelection == .useAllValidPhotos else {
            return applyFrameBudgetNormally(to: groups, targetCount: targetCount)
        }

        let photoCount = groups.filter { !$0.isVideo }.reduce(0) { $0 + $1.frames.count }
        let videoGroups = groups.filter(\.isVideo)
        let availableVideoCount = videoGroups.reduce(0) { $0 + $1.frames.count }
        let reservedVideoCount = min(
            availableVideoCount,
            RunPlanResolver.minimumReservedVideoFrameCount(
                keyframeBudget: targetCount,
                videoCount: videoGroups.count
            )
        )
        let maximumPhotoCount = max(0, targetCount - reservedVideoCount)
        guard photoCount <= maximumPhotoCount else {
            throw PipelineError.photoSelectionExceedsBudget(
                selected: photoCount,
                maximum: maximumPhotoCount
            )
        }
        let budgetedVideos = applyFrameBudgetNormally(
            to: videoGroups,
            targetCount: max(0, targetCount - photoCount)
        )
        let videoByID = Dictionary(
            budgetedVideos.map { ($0.id, $0) },
            uniquingKeysWith: { first, _ in first }
        )
        return groups.compactMap { group in
            if !group.isVideo { return group }
            return videoByID[group.id]
        }
    }

    private func applyFrameBudgetNormally(
        to groups: [SelectedFrameGroup],
        targetCount: Int
    ) -> [SelectedFrameGroup] {
        guard targetCount > 0 else { return [] }
        let total = groups.reduce(0) { $0 + $1.frames.count }
        guard total > targetCount else { return groups }

        struct FrameEntry {
            let groupIndex: Int
            let url: URL
        }

        let flattened = groups.enumerated().flatMap { groupIndex, group in
            group.frames.map { FrameEntry(groupIndex: groupIndex, url: $0) }
        }
        guard targetCount > 1 else {
            let entry = flattened[flattened.count / 2]
            let group = groups[entry.groupIndex]
            return [SelectedFrameGroup(id: group.id, frames: [entry.url], isVideo: group.isVideo)]
        }

        let step = Double(flattened.count - 1) / Double(targetCount - 1)
        var selectedByGroup = Array(repeating: [URL](), count: groups.count)
        for index in 0..<targetCount {
            let position = Int(round(Double(index) * step))
            let entry = flattened[position]
            selectedByGroup[entry.groupIndex].append(entry.url)
        }

        return groups.enumerated().compactMap { index, group in
            let frames = selectedByGroup[index]
            guard !frames.isEmpty else { return nil }
            return SelectedFrameGroup(id: group.id, frames: frames, isVideo: group.isVideo)
        }
    }

    func filterVeryBlurryVideoFrames(
        frames: [URL],
        sharpnessByFrame: [URL: Double],
        profile: FrameExtractionProfile,
        maxDropFraction: Double,
        floorScale: Double
    ) -> BlurFilterResult {
        guard !frames.isEmpty else { return BlurFilterResult(frames: [], dropped: 0) }
        let safeFraction = max(0.0, min(1.0, maxDropFraction))
        let maxDropCount = Int((Double(frames.count) * safeFraction).rounded(.down))
        guard maxDropCount > 0 else { return BlurFilterResult(frames: frames, dropped: 0) }
        let floor = max(0.0, profile.sharpnessFloor * floorScale)

        var candidates: [(URL, Double)] = []
        candidates.reserveCapacity(frames.count)
        for url in frames {
            guard let sharpness = sharpnessByFrame[url] else { continue }
            if sharpness < floor {
                candidates.append((url, sharpness))
            }
        }
        guard !candidates.isEmpty else { return BlurFilterResult(frames: frames, dropped: 0) }

        let toDrop: Set<URL>
        if candidates.count <= maxDropCount {
            toDrop = Set(candidates.map { $0.0 })
        } else {
            let worst = candidates.sorted { $0.1 < $1.1 }.prefix(maxDropCount)
            toDrop = Set(worst.map { $0.0 })
        }
        guard !toDrop.isEmpty else { return BlurFilterResult(frames: frames, dropped: 0) }
        let filtered = frames.filter { !toDrop.contains($0) }
        let dropped = frames.count - filtered.count
        return BlurFilterResult(frames: filtered, dropped: dropped)
    }

    func targetCountForVideo(index: Int, total: Int, targetCount: Int) -> Int {
        guard total > 0 else { return targetCount }
        let base = targetCount / total
        let remainder = targetCount % total
        return base + (index < remainder ? 1 : 0)
    }

    func persistCheckpoint(
        paths: ProjectPaths,
        stage: PipelineStage,
        progress: Double? = nil,
        message: String? = nil,
        details: PipelineCheckpointDetails? = nil
    ) {
        guard var metadata = try? ProjectMetadataStore.load(from: paths.metadataURL) else { return }
        metadata.checkpoint = PipelineCheckpoint(
            stage: stage,
            updatedAt: Date(),
            progressFraction: progress,
            message: message,
            details: details
        )
        // Use the notes-preserving save so a checkpoint written mid-run cannot clobber a note
        // the user edited since this metadata was loaded, matching every other in-run write.
        try? ProjectMetadataStore.savePreservingUserEditableFields(metadata, to: paths.metadataURL)
    }

    struct FrameExtractionProfile {
        let targetCount: Int
        let maxDimension: CGFloat
        let targetFPS: Int
        let minDistanceRatio: Double
        let sharpnessFloor: Double
        let sharpnessRatio: Double
        let outputFormat: FrameOutputFormat
        let maxExtractedFrames: Int?
    }

    func frameExtractionProfile(for plan: ResolvedRunPlan, detail: DetailProfile) -> FrameExtractionProfile {
        let minDistanceRatio: Double = switch plan.capturePath {
        case .orbit: 0.12
        case .automatic, .walkthrough: 0.20
        case .largeArea: 0.30
        }
        let sharpness: (floor: Double, ratio: Double) = switch detail {
        case .fast: (30, 0.50)
        case .balanced: (40, 0.60)
        case .highDetail: (50, 0.65)
        }
        return FrameExtractionProfile(
            targetCount: plan.keyframeBudget,
            maxDimension: CGFloat(plan.maximumImageDimension),
            targetFPS: plan.analysisFrameRate,
            minDistanceRatio: minDistanceRatio,
            sharpnessFloor: sharpness.floor,
            sharpnessRatio: sharpness.ratio,
            outputFormat: detail == .highDetail ? .png : .jpeg,
            maxExtractedFrames: max(
                plan.keyframeBudget,
                Int(ceil(Double(plan.keyframeBudget) / 0.75))
            )
        )
    }

    func cameraModel(
        detailProfile: DetailProfile,
        capturePath: CapturePath,
        lensProjection: LensProjection = .automatic
    ) -> String {
        switch lensProjection {
        case .fisheye:
            return "OPENCV_FISHEYE"
        case .perspective:
            return detailProfile == .highDetail ? "OPENCV" : "SIMPLE_RADIAL"
        case .automatic:
            break
        }
        if detailProfile == .highDetail,
           capturePath == .walkthrough || capturePath == .largeArea {
            return "OPENCV"
        }
        return "SIMPLE_RADIAL"
    }

    func shouldUseSequential(
        selectedFrames: [URL],
        input: InputSpec,
        forceExhaustive: Bool,
        pairingPolicy: ResolvedPairingPolicy? = nil
    ) -> Bool {
        if forceExhaustive { return false }
        if let pairingPolicy {
            guard pairingPolicy != .unorderedRetrieval else { return false }
            return selectedFrames.count >= 30
        }
        guard input.hasVideos, !input.hasPhotos else { return false }
        guard input.videoFiles.count == 1 else { return false }
        if selectedFrames.count < 30 { return false }
        return true
    }
}
